services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./migrations:/app/migrations
      - ./.env:/app/.env
    environment:
      DB_URL: "postgres://postgres:password@db:5432/postgres?sslmode=disable"
    entrypoint: ["/app/migrate", "-action", "up"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./migrations:/app/migrations
      - ./.env:/app/.env
    environment:
      DB_URL: "postgres://postgres:password@db:5432/postgres?sslmode=disable"
    entrypoint: ["/app/app"]

volumes:
  pgdata:
